import os

dict_path = r"c:\Users\ABDUL MANNAN\Downloads\CubyCare-main\CubyCare-main\app\src\main\java\co\csedge\cubycare\utils\AppTranslations.kt"

new_entries = """
        "settings_theme_title" to mapOf("en" to "App Color Theme & Palette", "hi" to "ऐप कलर थीम", "te" to "యాప్ కలర్ థీమ్", "ta" to "நிற தீம்", "kn" to "ಬಣ್ಣದ ಥೀಮ್", "ml" to "കളർ തീം", "mr" to "रंग थीम", "bn" to "রঙের থিম", "gu" to "રંગ થીમ", "pa" to "ਰੰਗ ਥੀਮ"),
        "settings_theme_select" to mapOf("en" to "Select App Color Theme", "hi" to "कलर थीम चुनें", "te" to "థీమ్‌ను ఎంచుకోండి", "ta" to "தீம் தேர்ந்தெடுக்கவும்", "kn" to "ಥೀಮ್ ಆಯ್ಕೆಮಾಡಿ", "ml" to "തീം തിരഞ്ഞെടുക്കുക", "mr" to "थीम निवडा", "bn" to "থিম নির্বাচন করুন", "gu" to "થીમ પસંદ કરો", "pa" to "ਥੀਮ ਚੁਣੋ"),
        "settings_theme_desc" to mapOf("en" to "Tap a theme palette below to customize the app appearance instantaneously:", "hi" to "ऐप को कस्टमाइज़ करने के लिए नीचे दिए गए थीम पर टैप करें:", "te" to "యాప్ రూపాన్ని అనుకూలీకరించడానికి థీమ్‌పై నొక్కండి:", "ta" to "தீம் மீது தட்டவும்:", "kn" to "ಥೀಮ್ ಅನ್ನು ಟ್ಯಾಪ್ ಮಾಡಿ:", "ml" to "തീമിൽ ടാപ്പ് ചെയ്യുക:", "mr" to "थीमवर टॅप करा:", "bn" to "থিম এ আলতো চাপুন:", "gu" to "થીમ પર ટેપ કરો:", "pa" to "ਥੀਮ ਤੇ ਟੈਪ ਕਰੋ:"),
        "settings_notif_title" to mapOf("en" to "Notifications & Reminders", "hi" to "सूचनाएं और रिमाइंडर", "te" to "నోటిఫికేషన్‌లు & రిమైండర్‌లు", "ta" to "அறிவிப்புகள்", "kn" to "ಅಧಿಸೂಚನೆಗಳು", "ml" to "അറിയിപ്പുകൾ", "mr" to "सूचना", "bn" to "বিজ্ঞপ্তি", "gu" to "સૂચનાઓ", "pa" to "ਸੂਚਨਾਵਾਂ"),
        "settings_notif_vaccine" to mapOf("en" to "Vaccine Due Reminders", "hi" to "वैक्सीन देय रिमाइंडर", "te" to "టీకా రిమైండర్‌లు", "ta" to "தடுப்பூசி நினைவூட்டல்கள்", "kn" to "ಲಸಿಕೆ ಜ್ಞಾಪನೆಗಳು", "ml" to "വാക്സിൻ ഓർമ്മപ്പെടുത്തലുകൾ", "mr" to "लस स्मरणपत्रे", "bn" to "টিকা অনুস্মারক", "gu" to "રસી રીમાઇન્ડર્સ", "pa" to "ਟੀਕਾ ਰੀਮਾਈਂਡਰ"),
        "settings_notif_vaccine_desc" to mapOf("en" to "Alerts 7 days before upcoming vaccine dates", "hi" to "टीकाकरण से 7 दिन पहले अलर्ट", "te" to "7 రోజుల ముందు అలర్ట్‌లు", "ta" to "7 நாட்களுக்கு முன்பு எச்சரிக்கைகள்", "kn" to "7 ದಿನಗಳ ಮೊದಲು ಎಚ್ಚರಿಕೆಗಳು", "ml" to "7 ദിവസം മുമ്പ് അലർട്ടുകൾ", "mr" to "7 दिवसांपूर्वी अलर्ट", "bn" to "৭ দিন আগে সতর্কতা", "gu" to "7 દિવસ પહેલા ચેતવણીઓ", "pa" to "7 ਦਿਨ ਪਹਿਲਾਂ ਅਲਰਟ"),
        "settings_notif_med" to mapOf("en" to "Medicine Tracker Alerts", "hi" to "मेडिसिन ट्रैकर अलर्ट", "te" to "మెడిసిన్ ట్రాకర్ అలర్ట్‌లు", "ta" to "மருந்து கண்காணிப்பு எச்சரிக்கைகள்", "kn" to "ಔಷಧಿ ಎಚ್ಚರಿಕೆಗಳು", "ml" to "മരുന്ന് അലർട്ടുകൾ", "mr" to "औषध अलर्ट", "bn" to "ওষুধ সতর্কতা", "gu" to "દવા ચેતવણીઓ", "pa" to "ਦਵਾਈ ਅਲਰਟ"),
        "settings_notif_med_desc" to mapOf("en" to "Push notifications for active medicine doses", "hi" to "सक्रिय दवा खुराक के लिए सूचनाएं", "te" to "యాక్టివ్ మెడిసిన్ డోస్‌ల కోసం నోటిఫికేషన్‌లు", "ta" to "செயலில் உள்ள மருந்து அளவுகளுக்கான அறிவிப்புகள்", "kn" to "ಔಷಧಿಗಳಿಗಾಗಿ ಅಧಿಸೂಚನೆಗಳು", "ml" to "മരുന്നുകൾക്കുള്ള അറിയിപ്പുകൾ", "mr" to "औषधांसाठी सूचना", "bn" to "ওষুধের জন্য বিজ্ঞপ্তি", "gu" to "દવાઓ માટે સૂચનાઓ", "pa" to "ਦਵਾਈਆਂ ਲਈ ਸੂਚਨਾਵਾਂ"),
        "settings_notif_tips" to mapOf("en" to "Daily Care & Joy Tips", "hi" to "दैनिक देखभाल और टिप्स", "te" to "రోజువారీ సంరక్షణ & చిట్కాలు", "ta" to "தினசரி பராமரிப்பு குறிப்புகள்", "kn" to "ದೈನಂದಿನ ಕಾಳಜಿ ಸಲಹೆಗಳು", "ml" to "ദൈനംദിന പരിചരണ നുറുങ്ങുകൾ", "mr" to "दैनंदिन काळजी टिप्स", "bn" to "দৈনিক যত্ন টিপস", "gu" to "દૈનિક સંભાળ ટિપ્સ", "pa" to "ਰੋਜ਼ਾਨਾ ਦੇਖਭਾਲ ਸੁਝਾਅ"),
        "settings_notif_tips_desc" to mapOf("en" to "Get pediatric tips for growth & naps", "hi" to "बाल रोग विशेषज्ञ के टिप्स प्राप्त करें", "te" to "పీడియాట్రిక్ చిట్కాలను పొందండి", "ta" to "குழந்தை மருத்துவ குறிப்புகளைப் பெறுக", "kn" to "ಮಕ್ಕಳ ಸಲಹೆಗಳನ್ನು ಪಡೆಯಿರಿ", "ml" to "കുട്ടികളുടെ നുറുങ്ങുകൾ നേടുക", "mr" to "मुलांच्या टिप्स मिळवा", "bn" to "শিশুদের টিপস পান", "gu" to "બાળકોની ટિપ્સ મેળવો", "pa" to "ਬੱਚਿਆਂ ਦੇ ਸੁਝਾਅ ਪ੍ਰਾਪਤ ਕਰੋ"),
        "settings_notif_growth" to mapOf("en" to "Monthly Growth Milestone Logins", "hi" to "मासिक विकास लॉगइन", "te" to "నెలవారీ వృద్ధి లాగిన్‌లు", "ta" to "மாதாந்திர வளர்ச்சி", "kn" to "ಮಾಸಿಕ ಬೆಳವಣಿಗೆ", "ml" to "പ്രതിമാസ വളർച്ച", "mr" to "मासिक वाढ", "bn" to "মাসিক বৃদ্ধি", "gu" to "માસિક વિકાસ", "pa" to "ਮਾਸਿਕ ਵਾਧਾ"),
        "settings_notif_growth_desc" to mapOf("en" to "Reminders to log height & weight updates", "hi" to "ऊंचाई और वजन अपडेट करने के लिए रिमाइंडर", "te" to "ఎత్తు & బరువు లాగ్ చేయడానికి రిమైండర్‌లు", "ta" to "உயரம் & எடையை பதிவு செய்ய நினைவூட்டல்கள்", "kn" to "ಎತ್ತರ ಮತ್ತು ತೂಕವನ್ನು ನಮೂದಿಸಲು ಜ್ಞಾಪನೆಗಳು", "ml" to "ഉയരവും ഭാരവും രേഖപ്പെടുത്താൻ ഓർമ്മപ്പെടുത്തലുകൾ", "mr" to "उंची आणि वजन नोंदवण्यासाठी स्मरणपत्रे", "bn" to "উচ্চতা ও ওজন লগ করার অনুস্মারক", "gu" to "ઊંચાઈ અને વજન નોંધવા માટે રીમાઇન્ડર્સ", "pa" to "ਉਚਾਈ ਅਤੇ ਭਾਰ ਦਰਜ ਕਰਨ ਲਈ ਰੀਮਾਈਂਡਰ"),
        "settings_units_title" to mapOf("en" to "Units & Measurements", "hi" to "इकाइयां और मापन", "te" to "యూనిట్లు & కొలతలు", "ta" to "அலகுகள்", "kn" to "ಘಟಕಗಳು", "ml" to "യൂണിറ്റുകൾ", "mr" to "युनिट्स", "bn" to "ইউনিট", "gu" to "એકમો", "pa" to "ਯੂਨਿਟ"),
        "settings_units_metric" to mapOf("en" to "Metric Units (kg, cm)", "hi" to "मीट्रिक इकाइयां (kg, cm)", "te" to "మెట్రిక్ యూనిట్లు (kg, cm)", "ta" to "மெட்ரிக் (kg, cm)", "kn" to "ಮೆಟ್ರಿಕ್ (kg, cm)", "ml" to "മെട്രിക് (kg, cm)", "mr" to "मेट्रिक (kg, cm)", "bn" to "মেট্রিক (kg, cm)", "gu" to "મેટ્રિક (kg, cm)", "pa" to "ਮੀਟ੍ਰਿਕ (kg, cm)"),
        "settings_units_imperial" to mapOf("en" to "Imperial Units (lbs, inches)", "hi" to "इंपीरियल इकाइयां (lbs, inches)", "te" to "ఇంపీరియల్ యూనిట్లు (lbs, inches)", "ta" to "இம்பீரியல் (lbs, inches)", "kn" to "ಇಂಪೀರಿಯಲ್ (lbs, inches)", "ml" to "ഇംപീരിയൽ (lbs, inches)", "mr" to "इंपीरियल (lbs, inches)", "bn" to "ইম্পেরিয়াল (lbs, inches)", "gu" to "ઇમ્પીરીયલ (lbs, inches)", "pa" to "ਇੰਪੀਰੀਅਲ (lbs, inches)"),
        "settings_units_desc" to mapOf("en" to "Toggle between Metric (kg/cm) and Imperial (lbs/in)", "hi" to "मीट्रिक और इंपीरियल के बीच टॉगल करें", "te" to "మెట్రిక్ మరియు ఇంపీరియల్ మధ్య టోగుల్ చేయండి", "ta" to "மெட்ரிக் மற்றும் இம்பீரியல் இடையே மாற்றவும்", "kn" to "ಮೆಟ್ರಿಕ್ ಮತ್ತು ಇಂಪೀರಿಯಲ್ ನಡುವೆ ಬದಲಾಯಿಸಿ", "ml" to "മെട്രിക്, ഇംപീരിയൽ എന്നിവക്കിടയിൽ മാറ്റുക", "mr" to "मेट्रिक आणि इंपीरियल दरम्यान टॉगल करा", "bn" to "মেট্রিক এবং ইম্পেরিয়াল এর মধ্যে টগল করুন", "gu" to "મેટ્રિક અને ઇમ્પીરીયલ વચ્ચે ટૉગલ કરો", "pa" to "ਮੀਟ੍ਰਿਕ ਅਤੇ ਇੰਪੀਰੀਅਲ ਵਿਚਕਾਰ ਟੌਗਲ ਕਰੋ"),
        "settings_export_title" to mapOf("en" to "Data Export & Cloud Sync", "hi" to "डेटा निर्यात और क्लाउड सिंक", "te" to "డేటా ఎగుమతి & క్లౌడ్ సింక్", "ta" to "தரவு ஏற்றுமதி", "kn" to "ಡೇಟಾ ರಫ್ತು", "ml" to "ഡാറ്റ കയറ്റുമതി", "mr" to "डेटा निर्यात", "bn" to "ডেটা এক্সপোর্ট", "gu" to "ડેટા નિકાસ", "pa" to "ਡਾਟਾ ਐਕਸਪੋਰਟ"),
        "settings_export_sync" to mapOf("en" to "Cloud Backup & Sync Status", "hi" to "क्लाउड बैकअप", "te" to "క్లౌడ్ బ్యాకప్", "ta" to "கிளவுட் பேக்கப்", "kn" to "ಕ್ಲೌಡ್ ಬ್ಯಾಕಪ್", "ml" to "ക്ലൗഡ് ബാക്കപ്പ്", "mr" to "क्लाउड बॅकअप", "bn" to "ক্লাউড ব্যাকআপ", "gu" to "ક્લાઉડ બેકઅપ", "pa" to "ਕਲਾਉਡ ਬੈਕਅੱਪ"),
        "settings_export_sync_desc" to mapOf("en" to "Auto-synced to secure Firebase account", "hi" to "फायरबेस खाते में ऑटो-सिंक किया गया", "te" to "ఆటో-సింక్ చేయబడింది", "ta" to "தானாக ஒத்திசைக்கப்பட்டது", "kn" to "ಸ್ವಯಂ ಸಿಂಕ್ ಮಾಡಲಾಗಿದೆ", "ml" to "ഓട്ടോ-സിങ്ക് ചെയ്തു", "mr" to "ऑटो-सिंक केले", "bn" to "স্বয়ংক্রিয় সিঙ্ক করা হয়েছে", "gu" to "સ્વતઃ સિંક થયું", "pa" to "ਆਟੋ-ਸਿੰਕ ਕੀਤਾ ਗਿਆ"),
        "settings_export_pdf" to mapOf("en" to "Export Medical Report Summary (Text/PDF)", "hi" to "चिकित्सा रिपोर्ट निर्यात करें (PDF)", "te" to "మెడికల్ రిపోర్ట్ ఎగుమతి చేయండి", "ta" to "மருத்துவ அறிக்கையை ஏற்றுமதி செய்", "kn" to "ವೈದ್ಯಕೀಯ ವರದಿಯನ್ನು ರಫ್ತು ಮಾಡಿ", "ml" to "മെഡിക്കൽ റിപ്പോർട്ട് കയറ്റുമതി ചെയ്യുക", "mr" to "वैद्यकीय अहवाल निर्यात करा", "bn" to "মেডিকেল রিপোর্ট এক্সপোর্ট করুন", "gu" to "તબીબી અહેવાલ નિકાસ કરો", "pa" to "ਮੈਡੀਕਲ ਰਿਪੋਰਟ ਐਕਸਪੋਰਟ ਕਰੋ"),
        "settings_export_pdf_desc" to mapOf("en" to "Share report via WhatsApp, Email, or Files", "hi" to "व्हाट्सएप या ईमेल के माध्यम से साझा करें", "te" to "WhatsApp లేదా ఇమెయిల్ ద్వారా భాగస్వామ్యం చేయండి", "ta" to "WhatsApp மூலம் பகிரவும்", "kn" to "WhatsApp ಮೂಲಕ ಹಂಚಿಕೊಳ್ಳಿ", "ml" to "WhatsApp വഴി പങ്കിടുക", "mr" to "WhatsApp द्वारे शेअर करा", "bn" to "WhatsApp এর মাধ্যমে শেয়ার করুন", "gu" to "WhatsApp દ્વારા શેર કરો", "pa" to "WhatsApp ਰਾਹੀਂ ਸਾਂਝਾ ਕਰੋ"),
        "settings_export_csv" to mapOf("en" to "Export Child Data Sheet (CSV File)", "hi" to "डेटा शीट निर्यात करें (CSV)", "te" to "డేటా షీట్ ఎగుమతి చేయండి (CSV)", "ta" to "தரவு தாளை ஏற்றுமதி செய் (CSV)", "kn" to "ಡೇಟಾ ಶೀಟ್ ರಫ್ತು ಮಾಡಿ (CSV)", "ml" to "ഡാറ്റ ഷീറ്റ് കയറ്റുമതി ചെയ്യുക (CSV)", "mr" to "डेटा शीट निर्यात करा (CSV)", "bn" to "ডেটা শিট এক্সপোর্ট করুন (CSV)", "gu" to "ડેટા શીટ નિકાસ કરો (CSV)", "pa" to "ਡਾਟਾ ਸ਼ੀਟ ਐਕਸਪੋਰਟ ਕਰੋ (CSV)"),
        "settings_export_csv_desc" to mapOf("en" to "Download raw CSV file for doctors & clinics", "hi" to "डॉक्टरों के लिए CSV फ़ाइल डाउनलोड करें", "te" to "వైద్యుల కోసం CSV ఫైల్‌ను డౌన్‌లోడ్ చేయండి", "ta" to "மருத்துவர்களுக்கான CSV கோப்பு", "kn" to "ವೈದ್ಯರಿಗಾಗಿ CSV ಫೈಲ್", "ml" to "ഡോക്ടർമാർക്കുള്ള CSV ഫയൽ", "mr" to "डॉक्टरांसाठी CSV फाइल", "bn" to "ডাক্তারদের জন্য CSV ফাইল", "gu" to "ડૉક્ટરો માટે CSV ફાઇલ", "pa" to "ਡਾਕਟਰਾਂ ਲਈ CSV ਫਾਈਲ"),
        "settings_support_title" to mapOf("en" to "Pediatric Support & User Guide", "hi" to "बाल चिकित्सा सहायता", "te" to "పీడియాట్రిక్ సపోర్ట్", "ta" to "குழந்தை மருத்துவ ஆதரவு", "kn" to "ಮಕ್ಕಳ ಬೆಂಬಲ", "ml" to "കുട്ടികളുടെ പിന്തുണ", "mr" to "मुलांचा सपोर्ट", "bn" to "শিশুদের সাপোর্ট", "gu" to "બાળકોનો આધાર", "pa" to "ਬੱਚਿਆਂ ਦਾ ਸਪੋਰਟ"),
        "settings_support_faq" to mapOf("en" to "CubyCare FAQ & User Guide", "hi" to "FAQ और यूजर गाइड", "te" to "FAQ మరియు యూజర్ గైడ్", "ta" to "FAQ மற்றும் பயனர் வழிகாட்டி", "kn" to "FAQ ಮತ್ತು ಬಳಕೆದಾರರ ಮಾರ್ಗದರ್ಶಿ", "ml" to "FAQ-ഉം ഉപയോക്തൃ ഗൈഡും", "mr" to "FAQ आणि वापरकर्ता मार्गदर्शक", "bn" to "FAQ এবং ইউজার গাইড", "gu" to "FAQ અને વપરાશકર્તા માર્ગદર્શિકા", "pa" to "FAQ ਅਤੇ ਯੂਜ਼ਰ ਗਾਈਡ"),
        "settings_support_faq_desc" to mapOf("en" to "Interactive guide for growth & vaccine tracking", "hi" to "विकास और वैक्सीन ट्रैकिंग के लिए इंटरैक्टिव गाइड", "te" to "ట్రాకింగ్ కోసం ఇంటరాక్టివ్ గైడ్", "ta" to "கண்காணிப்புக்கான ஊடாடும் வழிகாட்டி", "kn" to "ಟ್ರ್ಯಾಕಿಂಗ್‌ಗಾಗಿ ಸಂವಾದಾತ್ಮಕ ಮಾರ್ಗದರ್ಶಿ", "ml" to "ട്രാക്കിംഗിനായുള്ള ഇന്ററാക്ടീവ് ഗൈഡ്", "mr" to "ट्रॅकिंगसाठी परस्परसंवादी मार्गदर्शक", "bn" to "ট্র্যাকিংয়ের জন্য ইন্টারেক্টিভ গাইড", "gu" to "ટ્રેકિંગ માટે ઇન્ટરેક્ટિવ માર્ગદર્શિકા", "pa" to "ਟਰੈਕਿੰਗ ਲਈ ਇੰਟਰਐਕਟਿਵ ਗਾਈਡ"),
        "settings_support_contact" to mapOf("en" to "Contact Pediatric Support Team", "hi" to "बाल चिकित्सा सहायता टीम से संपर्क करें", "te" to "సపోర్ట్ టీమ్‌ను సంప్రదించండి", "ta" to "ஆதரவு குழுவைத் தொடர்பு கொள்ளவும்", "kn" to "ಬೆಂಬಲ ತಂಡವನ್ನು ಸಂಪರ್ಕಿಸಿ", "ml" to "പിന്തുണ ടീമുമായി ബന്ധപ്പെടുക", "mr" to "सपोर्ट टीमशी संपर्क साधा", "bn" to "সাপোর্ট টিমের সাথে যোগাযোগ করুন", "gu" to "આધાર ટીમનો સંપર્ક કરો", "pa" to "ਸਪੋਰਟ ਟੀਮ ਨਾਲ ਸੰਪਰક ਕਰੋ"),
        "settings_support_contact_desc" to mapOf("en" to "Email support@cubycare.com directly", "hi" to "सीधे ईमेल करें", "te" to "నేరుగా ఇమెయిల్ చేయండి", "ta" to "நேரடியாக மின்னஞ்சல் செய்யவும்", "kn" to "ನೇರವಾಗಿ ಇಮೇಲ್ ಮಾಡಿ", "ml" to "നേരിട്ട് ഇമെയിൽ ചെയ്യുക", "mr" to "थेट ईमेल करा", "bn" to "সরাসরি ইমেল করুন", "gu" to "સીધો ઇમેઇલ કરો", "pa" to "ਸਿੱਧਾ ਈਮੇਲ ਕਰੋ"),
        "settings_about_title" to mapOf("en" to "About Application", "hi" to "एप्लिकेशन के बारे में", "te" to "అప్లికేషన్ గురించి", "ta" to "பயன்பாடு பற்றி", "kn" to "ಅಪ್ಲಿಕೇಶನ್ ಬಗ್ಗೆ", "ml" to "അപ്ലിക്കേഷനെക്കുറിച്ച്", "mr" to "अर्जाबद्दल", "bn" to "অ্যাপ্লিকেশন সম্পর্কে", "gu" to "એપ્લિકેશન વિશે", "pa" to "ਐਪਲੀਕੇਸ਼ਨ ਬਾਰੇ"),
        "settings_about_version" to mapOf("en" to "CubyCare Version", "hi" to "क्युबीकेयर संस्करण", "te" to "క్యూబీకేర్ వెర్షన్", "ta" to "கியூபிகேர் பதிப்பு", "kn" to "ಕ್ಯೂಬಿಕೇರ್ ಆವೃತ್ತಿ", "ml" to "ക്യൂബികെയർ പതിപ്പ്", "mr" to "क्युबीकेअर आवृत्ती", "bn" to "কিউবিক্যার সংস্করণ", "gu" to "ક્યુબીકેર આવૃત્તિ", "pa" to "ਕਿਊਬੀਕੇਅਰ ਸੰਸਕਰਣ"),
        "settings_about_desc" to mapOf("en" to "Pediatric Health & Growth Companion", "hi" to "बाल चिकित्सा स्वास्थ्य साथी", "te" to "పీడియాట్రిక్ హెల్త్ కంపానియన్", "ta" to "குழந்தை மருத்துவ ஆரோக்கிய துணை", "kn" to "ಮಕ್ಕಳ ಆರೋಗ್ಯ ಒಡನಾಡಿ", "ml" to "കുട്ടികളുടെ ആരോഗ്യ സഹായി", "mr" to "बालरोग आरोग्य साथीदार", "bn" to "শিশুদের স্বাস্থ্য সঙ্গী", "gu" to "બાળ ચિકિત્સા આરોગ્ય સાથી", "pa" to "ਬੱਚਿਆਂ ਦੇ ਸਿਹਤ ਸਾਥੀ"),
        "settings_about_privacy" to mapOf("en" to "HIPAA & Data Privacy Protected", "hi" to "डेटा गोपनीयता सुरक्षित", "te" to "డేటా గోప్యత రక్షించబడింది", "ta" to "தரவு தனியுரிமை பாதுகாக்கப்படுகிறது", "kn" to "ಡೇಟಾ ಗೌಪ್ಯತೆ ರಕ್ಷಿಸಲಾಗಿದೆ", "ml" to "ഡാറ്റാ സ്വകാര്യത പരിരക്ഷിച്ചിരിക്കുന്നു", "mr" to "डेटा गोपनीयता संरक्षित", "bn" to "ডেটা গোপনীয়তা সুরক্ষিত", "gu" to "ડેટા ગોપનીયતા સુરક્ષિત", "pa" to "ਡਾਟਾ ਪ੍ਰਾਈਵੇਸੀ ਸੁਰੱਖਿਅਤ"),
        "settings_cache_cleared" to mapOf("en" to "Cache Cleared", "hi" to "कैशे साफ़ किया गया", "te" to "కాష్ క్లియర్ చేయబడింది", "ta" to "கேச் அழிக்கப்பட்டது", "kn" to "ಕ್ಯಾಶ್ ತೆರವುಗೊಳಿಸಲಾಗಿದೆ", "ml" to "കാഷെ മായ്ച്ചു", "mr" to "कॅशे साफ केले", "bn" to "ক্যাশে পরিষ্কার করা হয়েছে", "gu" to "કેશ સાફ થયું", "pa" to "ਕੈਸ਼ ਸਾਫ਼ ਕੀਤਾ ਗਿਆ"),
        "settings_cache_clear" to mapOf("en" to "Clear Temporary Storage", "hi" to "अस्थायी भंडारण साफ़ करें", "te" to "తాత్కాలిక నిల్వను క్లియర్ చేయండి", "ta" to "தற்காலிக சேமிப்பை அழிக்கவும்", "kn" to "ತಾತ್ಕಾಲಿಕ ಸಂಗ್ರಹಣೆಯನ್ನು ತೆರವುಗೊಳಿಸಿ", "ml" to "താൽക്കാലിക സംഭരണം മായ്ക്കുക", "mr" to "तात्पुरती साठवणूक साफ करा", "bn" to "অস্থায়ী স্টোরেজ পরিষ্কার করুন", "gu" to "કામચલાઉ સંગ્રહ સાફ કરો", "pa" to "ਅਸਥਾਈ ਸਟੋਰੇਜ ਸਾਫ਼ ਕਰੋ"),
        "settings_cache_cleared_desc" to mapOf("en" to "0 KB temporary cache", "hi" to "0 KB कैशे", "te" to "0 KB కాష్", "ta" to "0 KB கேச்", "kn" to "0 KB ಕ್ಯಾಶ್", "ml" to "0 KB കാഷെ", "mr" to "0 KB कॅशे", "bn" to "0 KB ক্যাশে", "gu" to "0 KB કેશ", "pa" to "0 KB ਕੈਸ਼"),
        "settings_cache_clear_desc" to mapOf("en" to "Free up temporary app cache", "hi" to "ऐप कैशे खाली करें", "te" to "యాప్ కాష్‌ను ఖాళీ చేయండి", "ta" to "பயன்பாட்டு கேச்சை விடுவிக்கவும்", "kn" to "ಅಪ್ಲಿಕೇಶನ್ ಕ್ಯಾಶ್ ಅನ್ನು ಮುಕ್ತಗೊಳಿಸಿ", "ml" to "ആപ്പ് കാഷെ സ്വതന്ത്രമാക്കുക", "mr" to "ॲप कॅशे मोकळा करा", "bn" to "অ্যাপ ক্যাশে মুক্ত করুন", "gu" to "એપ કેશ મુક્ત કરો", "pa" to "ਐਪ ਕੈਸ਼ ਖਾਲੀ ਕਰੋ"),
        "addchild_q_dob" to mapOf("en" to "When was $name born?", "hi" to "$name का जन्म कब हुआ था?", "te" to "$name ఎప్పుడు జన్మించారు?", "ta" to "$name எப்போது பிறந்தார்?", "kn" to "$name ಯಾವಾಗ ಜನಿಸಿದರು?", "ml" to "$name എപ്പോഴാണ് ജനിച്ചത്?", "mr" to "$name चा जन्म कधी झाला?", "bn" to "$name কবে জন্মগ্রহণ করেছিল?", "gu" to "$name નો જન્મ ક્યારે થયો હતો?", "pa" to "$name ਦਾ ਜਨਮ ਕਦੋਂ ਹੋਇਆ ਸੀ?"),
        "addchild_desc_dob" to mapOf("en" to "Enter the Date of Birth.", "hi" to "जन्म तिथि दर्ज करें।", "te" to "పుట్టిన తేదీని నమోదు చేయండి.", "ta" to "பிறந்த தேதியை உள்ளிடவும்.", "kn" to "ಹುಟ್ಟಿದ ದಿನಾಂಕವನ್ನು ನಮೂದಿಸಿ.", "ml" to "ജനനത്തീയതി നൽകുക.", "mr" to "जन्म तारीख प्रविष्ट करा.", "bn" to "জন্ম তারিখ লিখুন।", "gu" to "જન્મ તારીખ દાખલ કરો.", "pa" to "ਜਨਮ ਤਾਰੀਖ ਦਰਜ ਕਰੋ।"),
        "addchild_ph_dob" to mapOf("en" to "DD/MM/YYYY", "hi" to "दिन/महीना/वर्ष", "te" to "DD/MM/YYYY", "ta" to "DD/MM/YYYY", "kn" to "DD/MM/YYYY", "ml" to "DD/MM/YYYY", "mr" to "DD/MM/YYYY", "bn" to "DD/MM/YYYY", "gu" to "DD/MM/YYYY", "pa" to "DD/MM/YYYY"),
        "addchild_q_gender" to mapOf("en" to "What is $name's gender?", "hi" to "$name का लिंग क्या है?", "te" to "$name లింగం ఏమిటి?", "ta" to "$name இன் பாலினம் என்ன?", "kn" to "$name ನ ಲಿಂಗ ಏನು?", "ml" to "$name ന്റെ ലിംഗഭേദം എന്താണ്?", "mr" to "$name चे लिंग काय आहे?", "bn" to "$name এর লিঙ্গ কি?", "gu" to "$name નું લિંગ શું છે?", "pa" to "$name ਦਾ ਲਿੰਗ ਕੀ ਹੈ?"),
        "addchild_desc_optional" to mapOf("en" to "Optional.", "hi" to "वैकल्पिक।", "te" to "ఐచ్ఛికం.", "ta" to "விருப்பமானது.", "kn" to "ಐಚ್ಛಿಕ.", "ml" to "ഓപ്ഷണൽ.", "mr" to "पर्यायी.", "bn" to "ঐচ্ছিক।", "gu" to "વૈકલ્પિક.", "pa" to "ਵਿਕਲਪਿਕ।"),
        "addchild_ph_gender" to mapOf("en" to "Boy / Girl / Other", "hi" to "लड़का / लड़की / अन्य", "te" to "బాలుడు / బాలిక / ఇతర", "ta" to "சிறுவன் / சிறுமி / மற்றவை", "kn" to "ಹುಡುಗ / ಹುಡುಗಿ / ಇತರೆ", "ml" to "ആൺകുട്ടി / പെൺകുട്ടി / മറ്റുള്ളവ", "mr" to "मुलगा / मुलगी / इतर", "bn" to "ছেলে / মেয়ে / অন্যান্য", "gu" to "છોકરો / છોકરી / અન્ય", "pa" to "ਮੁੰਡਾ / ਕੁੜੀ / ਹੋਰ"),
        "addchild_q_weight" to mapOf("en" to "What was $name's birth weight?", "hi" to "$name का जन्म वजन क्या था?", "te" to "$name పుట్టినప్పుడు బరువు ఎంత?", "ta" to "$name இன் பிறந்த எடை என்ன?", "kn" to "$name ನ ಹುಟ್ಟಿದ ತೂಕ ಎಷ್ಟು?", "ml" to "$name ന്റെ ജനന ഭാരം എന്തായിരുന്നു?", "mr" to "$name चे जन्माचे वजन काय होते?", "bn" to "$name এর জন্মের সময় ওজন কত ছিল?", "gu" to "$name નું જન્મ સમયનું વજન શું હતું?", "pa" to "$name ਦਾ ਜਨਮ ਦਾ ਭਾਰ ਕੀ ਸੀ?"),
        "addchild_desc_weight" to mapOf("en" to "This helps us track growth accurately.", "hi" to "इससे हमें वृद्धि को ट्रैक करने में मदद मिलती है।", "te" to "ఇది వృద్ధిని ట్రాక్ చేయడంలో మాకు సహాయపడుతుంది.", "ta" to "இது வளர்ச்சியை கண்காணிக்க உதவுகிறது.", "kn" to "ಇದು ಬೆಳವಣಿಗೆಯನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.", "ml" to "വളർച്ച ട്രാക്കുചെയ്യാൻ ഇത് ഞങ്ങളെ സഹായിക്കുന്നു.", "mr" to "यामुळे आम्हाला वाढ ट्रॅक करण्यास मदत होते.", "bn" to "এটি আমাদের বৃদ্ধি ট্র্যাক করতে সাহায্য করে।", "gu" to "આ અમને વિકાસને ટ્રૅક કરવામાં મદદ કરે છે.", "pa" to "ਇਹ ਸਾਨੂੰ ਵਾਧੇ ਨੂੰ ਟਰੈਕ ਕਰਨ ਵਿੱਚ ਮਦਦ ਕਰਦਾ ਹੈ।"),
        "addchild_ph_weight" to mapOf("en" to "e.g., 3.2 kg", "hi" to "उदा., 3.2 kg", "te" to "ఉదా., 3.2 kg", "ta" to "எ.கா., 3.2 kg", "kn" to "ಉದಾ., 3.2 kg", "ml" to "ഉദാ., 3.2 kg", "mr" to "उदा., 3.2 kg", "bn" to "উদাঃ, 3.2 kg", "gu" to "દા.ત., 3.2 kg", "pa" to "ਉਦਾਹਰਣ, 3.2 kg"),
        "addchild_q_length" to mapOf("en" to "What was the birth length?", "hi" to "जन्म के समय लंबाई क्या थी?", "te" to "పుట్టినప్పుడు ఎత్తు ఎంత?", "ta" to "பிறந்த நீளம் என்ன?", "kn" to "ಹುಟ್ಟಿದ ಉದ್ದ ಎಷ್ಟು?", "ml" to "ജനന നീളം എന്തായിരുന്നു?", "mr" to "जन्माची लांबी काय होती?", "bn" to "জন্মের দৈর্ঘ্য কত ছিল?", "gu" to "જન્મ સમયની લંબાઈ શું હતી?", "pa" to "ਜਨਮ ਦੀ ਲੰਬਾਈ ਕੀ ਸੀ?"),
        "addchild_desc_length" to mapOf("en" to "Length or height at birth.", "hi" to "जन्म के समय लंबाई या ऊंचाई।", "te" to "పుట్టినప్పుడు ఎత్తు.", "ta" to "பிறந்த போது நீளம் அல்லது உயரம்.", "kn" to "ಹುಟ್ಟಿದಾಗ ಉದ್ದ ಅಥವಾ ಎತ್ತರ.", "ml" to "ജനന സമയത്തെ നീളം അല്ലെങ്കിൽ ഉയരം.", "mr" to "जन्माच्या वेळी लांबी किंवा उंची.", "bn" to "জন্মের সময় দৈর্ঘ্য বা উচ্চতা।", "gu" to "જન્મ સમયે લંબાઈ અથવા ઊંચાઈ.", "pa" to "ਜਨਮ ਸਮੇਂ ਲੰਬਾਈ ਜਾਂ ਉਚਾਈ।"),
        "addchild_ph_length" to mapOf("en" to "e.g., 50 cm", "hi" to "उदा., 50 cm", "te" to "ఉదా., 50 cm", "ta" to "எ.கா., 50 cm", "kn" to "ಉದಾ., 50 cm", "ml" to "ഉദാ., 50 cm", "mr" to "उदा., 50 cm", "bn" to "উদাঃ, 50 cm", "gu" to "દા.ત., 50 cm", "pa" to "ਉਦਾਹਰਣ, 50 cm"),
        "addchild_q_head" to mapOf("en" to "Head circumference at birth?", "hi" to "जन्म के समय सिर की परिधि?", "te" to "పుట్టినప్పుడు తల చుట్టుకొలత?", "ta" to "பிறந்த போது தலை சுற்றளவு?", "kn" to "ಹುಟ್ಟಿದಾಗ ತಲೆಯ ಸುತ್ತಳತೆ?", "ml" to "ജനന സമയത്തെ തലയുടെ ചുറ്റളവ്?", "mr" to "जन्माच्या वेळी डोक्याचा घेर?", "bn" to "জন্মের সময় মাথার পরিধি?", "gu" to "જન્મ સમયે માથાનો પરિઘ?", "pa" to "ਜਨਮ ਸਮੇਂ ਸਿਰ ਦਾ ਘੇਰਾ?"),
        "addchild_desc_head" to mapOf("en" to "Important for early development tracking.", "hi" to "प्रारंभिक विकास ट्रैकिंग के लिए महत्वपूर्ण।", "te" to "ప్రారంభ అభివృద్ధి ట్రాకింగ్ కోసం ముఖ్యం.", "ta" to "ஆரம்ப வளர்ச்சி கண்காணிப்புக்கு முக்கியமானது.", "kn" to "ಆರಂಭಿಕ ಅಭಿವೃದ್ಧಿ ಟ್ರ್ಯಾಕಿಂಗ್‌ಗೆ ಮುಖ್ಯವಾಗಿದೆ.", "ml" to "ആദ്യകാല വികസന ട്രാക്കിംഗിന് പ്രധാനമാണ്.", "mr" to "सुरुवातीच्या विकासासाठी महत्वाचे.", "bn" to "প্রাথমিক বিকাশ ট্র্যাকিংয়ের জন্য গুরুত্বপূর্ণ।", "gu" to "પ્રારંભિક વિકાસ ટ્રેકિંગ માટે મહત્વપૂર્ણ.", "pa" to "ਸ਼ੁਰੂਆਤੀ ਵਿਕਾਸ ਟਰੈਕਿੰਗ ਲਈ ਮਹੱਤਵਪੂਰਨ।"),
        "addchild_ph_head" to mapOf("en" to "e.g., 35 cm", "hi" to "उदा., 35 cm", "te" to "ఉదా., 35 cm", "ta" to "எ.கா., 35 cm", "kn" to "ಉದಾ., 35 cm", "ml" to "ഉദാ., 35 cm", "mr" to "उदा., 35 cm", "bn" to "উদাঃ, 35 cm", "gu" to "દા.ત., 35 cm", "pa" to "ਉਦਾਹਰਣ, 35 cm"),
        "addchild_q_blood" to mapOf("en" to "What is $name's blood group?", "hi" to "$name का रक्त समूह क्या है?", "te" to "$name రక్త వర్గం ఏమిటి?", "ta" to "$name இன் இரத்த வகை என்ன?", "kn" to "$name ನ ರಕ್ತದ ಗುಂಪು ಯಾವುದು?", "ml" to "$name ന്റെ രക്ത ഗ്രൂപ്പ് എന്താണ്?", "mr" to "$name चा रक्तगट काय आहे?", "bn" to "$name এর রক্তের গ্রুপ কি?", "gu" to "$name નું રક્ત જૂથ શું છે?", "pa" to "$name ਦਾ ਬਲੱਡ ਗਰੁੱਪ ਕੀ ਹੈ?"),
        "addchild_desc_blood" to mapOf("en" to "Good to have on record.", "hi" to "रिकॉर्ड पर होना अच्छा है।", "te" to "రికార్డులో ఉంచడం మంచిది.", "ta" to "பதிவில் வைத்திருப்பது நல்லது.", "kn" to "ದಾಖಲೆಯಲ್ಲಿ ಇಡುವುದು ಒಳ್ಳೆಯದು.", "ml" to "റെക്കോർഡിൽ സൂക്ഷിക്കുന്നത് നല്ലതാണ്.", "mr" to "नोंदीत ठेवणे चांगले.", "bn" to "রেকর্ডে রাখা ভালো।", "gu" to "રેકોર્ડમાં રાખવું સારું છે.", "pa" to "ਰਿਕਾਰਡ 'ਤੇ ਰੱਖਣਾ ਚੰਗਾ ਹੈ।"),
        "addchild_ph_blood" to mapOf("en" to "e.g., O+, A-", "hi" to "उदा., O+, A-", "te" to "ఉదా., O+, A-", "ta" to "எ.கா., O+, A-", "kn" to "ಉದಾ., O+, A-", "ml" to "ഉദാ., O+, A-", "mr" to "उदा., O+, A-", "bn" to "উদাঃ, O+, A-", "gu" to "દા.ત., O+, A-", "pa" to "ਉਦਾਹਰਣ, O+, A-"),
        "addchild_q_genetic" to mapOf("en" to "Any genetic issues?", "hi" to "कोई आनुवंशिक समस्या?", "te" to "ఏదైనా జన్యుపరమైన సమస్యలు ఉన్నాయా?", "ta" to "ஏதேனும் மரபணு சிக்கல்கள் உள்ளதா?", "kn" to "ಯಾವುದೇ ಆನುವಂಶಿಕ ಸಮಸ್ಯೆಗಳಿವೆಯೇ?", "ml" to "എന്തെങ്കിലും ജനിതക പ്രശ്നങ്ങൾ ഉണ്ടോ?", "mr" to "काही अनुवांशिक समस्या?", "bn" to "কোনো জেনেটিক সমস্যা আছে?", "gu" to "કોઈ આનુવંશિક સમસ્યાઓ?", "pa" to "ਕੋਈ ਜੈਨੇਟਿਕ ਸਮੱਸਿਆਵਾਂ?"),
        "addchild_desc_blank" to mapOf("en" to "Leave blank if none.", "hi" to "यदि कोई नहीं है तो खाली छोड़ दें।", "te" to "ఏమీ లేకుంటే ఖాళీగా వదిలివేయండి.", "ta" to "இல்லையென்றால் காலியாக விடவும்.", "kn" to "ಏನೂ ಇಲ್ಲದಿದ್ದರೆ ಖಾಲಿ ಬಿಡಿ.", "ml" to "ഒന്നുമില്ലെങ്കിൽ ശൂന്യമായി വിടുക.", "mr" to "काही नसल्यास रिक्त सोडा.", "bn" to "কিছু না থাকলে ফাঁকা রাখুন।", "gu" to "જો કંઈ ન હોય તો ખાલી છોડી દો.", "pa" to "ਜੇਕਰ ਕੋਈ ਨਹੀਂ ਤਾਂ ਖਾਲੀ ਛੱਡੋ।"),
        "addchild_ph_type" to mapOf("en" to "Type here...", "hi" to "यहां टाइप करें...", "te" to "ఇక్కడ టైప్ చేయండి...", "ta" to "இங்கே தட்டச்சு செய்யவும்...", "kn" to "ಇಲ್ಲಿ ಟೈಪ್ ಮಾಡಿ...", "ml" to "ഇവിടെ ടൈപ്പ് ചെയ്യുക...", "mr" to "येथे टाइप करा...", "bn" to "এখানে টাইপ করুন...", "gu" to "અહીં ટાઈપ કરો...", "pa" to "ਇੱਥੇ ਟਾਈਪ ਕਰੋ..."),
        "addchild_q_allergies" to mapOf("en" to "Does $name have any allergies?", "hi" to "क्या $name को कोई एलर्जी है?", "te" to "$name కి ఏదైనా అలెర్జీ ఉందా?", "ta" to "$name க்கு ஏதேனும் ஒவ்வாமை உள்ளதா?", "kn" to "$name ಗೆ ಯಾವುದೇ ಅಲರ್ಜಿ ಇದೆಯೇ?", "ml" to "$name ന് എന്തെങ്കിലും അലർജി ഉണ്ടോ?", "mr" to "$name ला काही अॅलर्जी आहे का?", "bn" to "$name এর কি কোনো অ্যালার্জি আছে?", "gu" to "શું $name ને કોઈ એલર્જી છે?", "pa" to "ਕੀ $name ਨੂੰ ਕੋਈ ਐਲਰਜੀ ਹੈ?"),
        "addchild_q_medical" to mapOf("en" to "Any medical conditions?", "hi" to "कोई चिकित्सीय स्थिति?", "te" to "ఏదైనా వైద్య పరిస్థితులు ఉన్నాయా?", "ta" to "ஏதேனும் மருத்துவ நிலைமைகள் உள்ளதா?", "kn" to "ಯಾವುದೇ ವೈದ್ಯಕೀಯ ಪರಿಸ್ಥಿತಿಗಳಿವೆಯೇ?", "ml" to "എന്തെങ്കിലും മെഡിക്കൽ അവസ്ഥകൾ ഉണ്ടോ?", "mr" to "काही वैद्यकीय परिस्थिती?", "bn" to "কোনো চিকিৎসা শর্ত আছে?", "gu" to "કોઈ તબીબી સ્થિતિઓ?", "pa" to "ਕੋਈ ਮੈਡੀਕਲ ਹਾਲਤਾਂ?"),
        "upload_photo" to mapOf("en" to "Upload Photo (Optional)", "hi" to "फोटो अपलोड करें", "te" to "ఫోటోను అప్‌లోడ్ చేయండి", "ta" to "புகைப்படத்தைப் பதிவேற்றவும்", "kn" to "ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ", "ml" to "ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക", "mr" to "फोटो अपलोड करा", "bn" to "ছবি আপলোড করুন", "gu" to "ફોટો અપલોડ કરો", "pa" to "ਫੋਟੋ ਅੱਪਲੋਡ ਕਰੋ"),
        "change_photo" to mapOf("en" to "Change Photo", "hi" to "फोटो बदलें", "te" to "ఫోటోను మార్చండి", "ta" to "புகைப்படத்தை மாற்றவும்", "kn" to "ಫೋಟೋ ಬದಲಾಯಿಸಿ", "ml" to "ഫോട്ടോ മാറ്റുക", "mr" to "फोटो बदला", "bn" to "ছবি পরিবর্তন করুন", "gu" to "ફોટો બદલો", "pa" to "ਫੋਟੋ ਬਦਲੋ")
"""

with open(dict_path, 'r', encoding='utf-8') as f:
    content = f.read()

# Insert new entries right before the last closing brace
last_brace_idx = content.rfind(")")
new_content = content[:last_brace_idx] + ",\n" + new_entries + content[last_brace_idx:]

with open(dict_path, 'w', encoding='utf-8') as f:
    f.write(new_content)

print("AppTranslations updated successfully!")
